const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const frontendRoot = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(frontendRoot, file), 'utf8');

test('gallery page renders as a premium curated viewing experience', () => {
  const galleryHtml = read('gallery.html');
  const galleryJs = read('js/gallery.js');
  const css = read('style.css');

  assert.match(galleryHtml, /body class="gallery-page bg-body"/);
  assert.match(galleryHtml, /hero-section gallery-hero/);
  assert.match(galleryHtml, /<h1 class="display-2 text-uppercase text-dark">Gallery<\/h1>/);
  assert.match(galleryHtml, /aria-label="Gallery path"/);
  assert.match(galleryHtml, /<a href="index\.html">Home<\/a>[\s\S]{0,120}<span class="item" aria-hidden="true">&gt;<\/span>/);
  assert.doesNotMatch(galleryHtml, /aria-hidden="true">\/<\/span>/);
  assert.match(galleryHtml, /gallery-experience/);
  assert.match(galleryHtml, /gallery-filter-dock/);
  assert.match(galleryHtml, /gallery-filter-rail/);
  assert.match(galleryHtml, /gallery-filter-button active/);
  assert.match(galleryHtml, /gallery-filter-actions/);
  assert.match(galleryHtml, /id="gallery-result-count" class="gallery-result-count" aria-live="polite">Loading works\.\.\.<\/span>/);
  assert.match(galleryHtml, /gallery-artwork-grid/);
  assert.doesNotMatch(galleryHtml, /<h5>Filter by Category:<\/h5>/);

  assert.match(galleryJs, /gallery-artwork-item/);
  assert.match(galleryJs, /gallery-artwork-card/);
  assert.match(galleryJs, /gallery-artwork-record/);
  assert.match(galleryJs, /gallery-card-surface/);
  assert.match(galleryJs, /gallery-record-media/);
  assert.match(galleryJs, /gallery-record-body/);
  assert.match(galleryJs, /gallery-record-meta/);
  assert.match(galleryJs, /gallery-art-frame/);
  assert.match(galleryJs, /gallery-art-image/);
  assert.match(galleryJs, /gallery-card-caption/);
  assert.match(galleryJs, /gallery-card-note/);
  assert.match(galleryJs, /gallery-view-link/);
  assert.match(galleryJs, /createGalleryCardNote/);
  assert.match(galleryJs, /index < 2 \? 'eager' : 'lazy'/);
  assert.match(galleryJs, /fetchpriority/);
  assert.match(galleryJs, /srcset:\s*imageSources\.srcset/);
  assert.match(galleryJs, /sizes:\s*'\(max-width: 767px\) 92vw, \(max-width: 1199px\) 44vw, 24vw'/);
  assert.match(galleryJs, /function getArtworkImageSources\(artwork\)/);
  assert.match(galleryJs, /formats\?\.large/);
  assert.match(galleryJs, /formats\?\.medium/);
  assert.match(galleryJs, /formats\?\.small/);
  assert.match(galleryJs, /col-12 col-xl-6/);
  assert.match(galleryJs, /formatGalleryResultCount/);
  assert.match(galleryJs, /getCategoryArtworkCount/);
  assert.match(galleryJs, /initGalleryCardInteractions/);
  assert.match(galleryJs, /IntersectionObserver/);
  assert.doesNotMatch(galleryJs, /object-fit:\s*cover/);
  assert.doesNotMatch(galleryJs, /height:\s*300px/);
  assert.doesNotMatch(galleryJs, /text-box/);
  assert.doesNotMatch(galleryJs, /box-slide/);
  assert.doesNotMatch(galleryJs, /product-card/);
  assert.doesNotMatch(galleryJs, /gallery-description-teaser/);
  assert.doesNotMatch(galleryJs, /gallery-museum-label/);
  assert.doesNotMatch(galleryJs, /positionGalleryMuseumLabel/);
  assert.doesNotMatch(galleryJs, /gallery-matte-label/);
  assert.doesNotMatch(galleryJs, /gallery-reading-bar/);
  assert.doesNotMatch(galleryJs, /createGalleryMatteLabel/);
  assert.doesNotMatch(galleryJs, /showGalleryMatteLabel/);
  assert.doesNotMatch(galleryJs, /positionGalleryMatteLabel/);
  assert.doesNotMatch(galleryJs, /getRenderedImageBounds/);
  assert.doesNotMatch(galleryJs, /getMattePlacement/);
  assert.doesNotMatch(galleryJs, /showGalleryReadingBar/);
  assert.doesNotMatch(galleryJs, /hideGalleryMatteLabel/);
  assert.doesNotMatch(galleryJs, /updateGalleryDescriptionFade/);
  assert.doesNotMatch(galleryJs, /data-label-description/);
  assert.doesNotMatch(galleryJs, /uses-reading-bar/);
  assert.doesNotMatch(galleryJs, /gallery-label-active/);
  assert.doesNotMatch(galleryJs, /gallery-matte-label-title/);
  assert.doesNotMatch(galleryJs, /gallery-matte-label-meta/);
  assert.doesNotMatch(galleryJs, /gallery-reading-bar-title/);
  assert.doesNotMatch(galleryJs, /gallery-reading-bar-meta/);
  assert.doesNotMatch(galleryJs, /data-label-title/);
  assert.doesNotMatch(galleryJs, /data-label-meta/);

  assert.match(css, /\.gallery-page\s+#header\s*\{/s);
  assert.match(css, /\.gallery-hero\.hero-section/s);
  assert.match(css, /\.gallery-experience/s);
  assert.match(css, /\.gallery-filter-dock/s);
  assert.match(css, /\.gallery-filter-button/s);
  assert.match(css, /\.gallery-artwork-grid/s);
  assert.match(css, /\.gallery-artwork-card/s);
  assert.match(css, /\.gallery-artwork-card\.is-revealed/s);
  assert.match(css, /\.gallery-card-surface\s*{[^}]*display:\s*grid;/s);
  assert.match(css, /\.gallery-card-surface\s*{[^}]*grid-template-columns:\s*minmax/s);
  assert.match(css, /\.gallery-card-surface\s*{[^}]*border:\s*1px solid transparent;/s);
  assert.match(css, /linear-gradient\(145deg,\s*rgba\(var\(--bs-primary-rgb\),\s*0\.14\)/s);
  assert.match(css, /\.gallery-record-media/s);
  assert.match(css, /\.gallery-record-body/s);
  assert.match(css, /\.gallery-record-meta/s);
  assert.match(css, /\.gallery-art-frame/s);
  assert.match(css, /\.gallery-art-image\s*{[^}]*object-fit:\s*contain;/s);
  assert.match(css, /\.gallery-card-note\s*{[^}]*font-size:/s);
  assert.match(css, /\.gallery-card-note\s*{[^}]*line-height:\s*1\.7;/s);
  assert.match(css, /\.gallery-card-note\s*{[^}]*overflow-wrap:\s*break-word;/s);
  assert.match(css, /@media \(max-width: 767px\)[\s\S]*\.gallery-card-surface\s*{[\s\S]*max-width:\s*100%;/s);
  assert.match(css, /@media \(max-width: 767px\)[\s\S]*\.gallery-art-image\s*{[\s\S]*max-width:\s*100%;/s);
  assert.doesNotMatch(css, /\.gallery-museum-label/);
  assert.doesNotMatch(css, /\.gallery-matte-label/);
  assert.doesNotMatch(css, /\.gallery-reading-bar/);
  assert.doesNotMatch(css, /\.gallery-artwork-card\.is-matte-label-active/);
  assert.doesNotMatch(css, /body\.gallery-label-active/);
  assert.doesNotMatch(css, /\.gallery-matte-label-title/);
  assert.doesNotMatch(css, /\.gallery-matte-label-meta/);
  assert.doesNotMatch(css, /\.gallery-reading-bar-title/);
  assert.doesNotMatch(css, /\.gallery-reading-bar-meta/);
  assert.doesNotMatch(css, /\.gallery-card-note[\s\S]{0,500}-webkit-line-clamp/);
  assert.doesNotMatch(css, /\.gallery-card-note[\s\S]{0,500}max-height/);
  assert.doesNotMatch(css, /\.gallery-matte-label-description[\s\S]{0,500}-webkit-line-clamp/);
  assert.doesNotMatch(css, /\.gallery-reading-bar-description[\s\S]{0,500}-webkit-line-clamp/);
  assert.doesNotMatch(galleryHtml + galleryJs + css, /Read full note|View full note/i);
  assert.doesNotMatch(css, /\.gallery-artwork-card:hover\s+\.gallery-description-teaser/);
  assert.doesNotMatch(css, /\.gallery-description-teaser\s*{[\s\S]*max-height:\s*0/);
  assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)[\s\S]*\.gallery-artwork-card/);
});

test('gallery discovery controls and featured works use an accessible editorial treatment', () => {
  const galleryHtml = read('gallery.html');
  const galleryJs = read('js/gallery.js');
  const css = read('style.css');

  assert.match(galleryHtml, /id="gallery-search"/);
  assert.match(galleryHtml, /aria-label="Search artworks"/);
  assert.match(galleryHtml, /js\/artwork-discovery\.js/);
  assert.match(galleryJs, /getPopulatedCategories/);
  assert.match(galleryJs, /filterArtworks/);
  assert.match(galleryJs, /currentCategory === 'all' && !currentGallerySearch\.trim\(\)/);
  assert.match(galleryJs, /gallery-featured-mark/);
  assert.match(galleryJs, /is-featured/);
  assert.match(css, /\.gallery-artwork-card\.is-featured/);
  assert.match(css, /\.gallery-featured-mark/);
  assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)/);
});

test('series artworks keep the gallery layout while receiving restrained series context', () => {
  const detailHtml = read('artwork-detail.html');
  const detailJs = read('js/artwork-detail.js');
  const galleryJs = read('js/gallery.js');
  const css = read('style.css');

  assert.match(galleryJs, /galleryDiscovery\.getArtworkSeriesName\(artwork\)/);
  assert.match(galleryJs, /\.toggleClass\('is-series', Boolean\(seriesName\)\)/);
  assert.match(galleryJs, /gallery-series-label/);
  assert.match(detailHtml, /id="artwork-series-context"/);
  assert.match(detailHtml, /js\/artwork-discovery\.js/);
  assert.match(detailJs, /renderSeriesContext\(data\)/);
  assert.match(css, /\.gallery-artwork-card\.is-series\s+\.gallery-card-surface/);
  assert.match(css, /\.gallery-series-label/);
  assert.match(css, /\.artwork-series-context/);
});
